# this action is based on https://github.com/kayac/ecspresso/blob/v2/action.yml and licensed under MIT License
# original license is https://github.com/kayac/ecspresso/blob/v2/LICENSE
# modify replace kayac/ecspresso to mashiike/redshift-credentials
inputs:
  version:
    description: "A version to install redshift-credentials"
    default: latest
    required: false
  version-file:
    description: "File containing the redshift-credentials version. Example: .redshift-credentials-version"
    required: false
  github-token:
    description: "The token used when calling GitHub API"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        github_token: ${{ inputs.github-token }}
      run: |
        set -e
        VERSION="${{ inputs.version }}"
        if [ -n "${{ inputs.version-file }}" ]; then
          VERSION="v$(cat ${{ inputs.version-file }})"
        fi
        api_request_args=("-sS")
        if [[ -n "$github_token" ]]; then
          api_request_args=("${api_request_args[@]}" -H "authorization: token $github_token")
        fi
        if [ "${VERSION}" = "latest" ]; then
          DOWNLOAD_URL=$(curl "${api_request_args[@]}" https://api.github.com/repos/mashiike/redshift-credentials/releases | jq -r '[.[]|select(.tag_name > "v2.0")|select(.prerelease==false)][0].assets[].browser_download_url|select(match("linux.amd64."))')
        else
          DOWNLOAD_URL=https://github.com/mashiike/redshift-credentials/releases/download/${VERSION}/redshift-credentials_${VERSION:1}_linux_amd64.tar.gz
        fi
        mkdir -p ${RUNNER_TOOL_CACHE}/redshift-credentials
        cd /tmp
        curl -sfLO ${DOWNLOAD_URL}
        if [[ "${DOWNLOAD_URL}" =~ \.tar\.gz$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .tar.gz)
          tar xzvf ${FILENAME}.tar.gz
          sudo install redshift-credentials ${RUNNER_TOOL_CACHE}/redshift-credentials/redshift-credentials
        elif [[ "${DOWNLOAD_URL}" =~ \.zip$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .zip)
          unzip ${FILENAME}.zip
          sudo install ${FILENAME} ${RUNNER_TOOL_CACHE}/redshift-credentials/redshift-credentials
        fi

        echo "Adding ${RUNNER_TOOL_CACHE}/redshift-credentials to path..."
        echo "${RUNNER_TOOL_CACHE}/redshift-credentials" >> $GITHUB_PATH
        "${RUNNER_TOOL_CACHE}/redshift-credentials/redshift-credentials" --help
