name: test action
on:
  push:
    branches:
      - main
      - actions/**
  workflow_dispatch:

jobs:
  install:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mashiike/redshift-credentials@main
        with:
          version: v0.3.0
